### ISSUE TITLE
Use template without stripe

### ISSUE THREAD

**Issue by Surgical17** [nextjs/saas-starter#39]
Hi There

Unfortunately Stripe is not available in my country, but I would like to use and build from this template as a learning experience (Just using the DB, Dashboard Login etc.

How can I setup or change the setup.ts to create a db without stripe? Or will it be too much work to set it up without it?

**Comment by Anju023** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by baiwfg2** [comment]
I also have that need. When running `pnpm db:setup` , I encountered this issue:
```
$ pnpm db:setup

> @ db:setup D:\tmp\next-saas-starter-main
> npx tsx lib/db/setup.ts

Step 1: Checking if Stripe CLI is installed and authenticated...
Stripe CLI is not installed. Please install it and try again.
To install Stripe CLI, follow these steps:
1. Visit: https://docs.stripe.com/stripe-cli
2. Download and install the Stripe CLI for your operating system
3. After installation, run: stripe login
After installation and authentication, please run this setup script again.
 ELIFECYCLE  Command failed with exit code 1.
```
